---
title: 'Graph 5: Finale'
author: ''
date: '2018-06-13'
slug: graph-5-finale
categories: []
tags: []
description: Desc
hacker_news_id: ''
lobsters_id: ''
meta_img: /images/image.jpg
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
#library(ggalt)
library(ggradar)
library(extrafont)
library(ggfortify)
library(infer)
library(forcats)
library(ggridges)
library(here)
library(scales)
```

```{r}
radar_colour=rep(c("#FF5A5F", "#FFB400", "#007A87",  "#8CE071", "#7B0051", 
                       "#00D1C1", "#FFAA91", "#B4A76C", "#9CA299", "#565A5C", "#00A04B", "#E54C20"), 100)

clusters <- read_csv(here('static','data','redditProject','centers'))

clusters <- clusters %>% 
  mutate_at(vars(starts_with('d')),rescale)
clusters

dlabels= c('verb, work, i','relative, cogmech, present','social, i, affect','ppron, pronoun, social','1 funct, pronoun, cogmech','5 affect, pos emotion, relative','7 money, cause, present','6 work, money, bio','9 percept, cogmech, negemo ','10 bio, work, cogmech','11 money, cogmech, bio')

ggradar(clusters[1,], grid.label.size = 5,
        group.point.size = 3,
        axis.label.size = 2,
        axis.labels = dlabels,
        legend.text.size = 9,
        group.colours = radar_colour)+
  ggtitle("point1")+
  theme(legend.position="bottom") + 
  theme(text=element_text(family='Lato')) 


ggradar(clusters[2,], grid.label.size = 5,
        group.point.size = 4,
        axis.label.size = 3,
        axis.labels = dlabels,
        legend.text.size = 9,
        group.colours = radar_colour[2])+
  ggtitle("point2")+
  theme(legend.position="bottom") + 
  theme(text=element_text(family='Lato')) 

ggradar(clusters[3,],grid.label.size = 5,
        group.point.size = 4,
        axis.label.size = 3,
        axis.labels = dlabels,
        legend.text.size = 9,
        group.colours = radar_colour[3])+
  ggtitle("point3")+
  theme(legend.position="bottom") + 
  theme(text=element_text(family='Lato')) 


ggradar(clusters[4,], grid.label.size = 5,
        group.point.size = 4,
        axis.label.size = 3,
        axis.labels = dlabels,
        legend.text.size = 9,
        group.colours = radar_colour[4])+
  ggtitle("point4")+
  theme(legend.position="bottom") + 
  theme(text=element_text(family='Lato')) 


ggradar(clusters[5,], grid.label.size = 5,
        group.point.size = 4,
        axis.label.size = 3,
        axis.labels = dlabels,
        legend.text.size = 9,
        group.colours = radar_colour[5])+
  ggtitle("point5")+
  theme(legend.position="bottom") + 
  theme(text=element_text(family='Lato')) 

          
          
ggradar(clusters[6,], grid.label.size = 5,
        group.point.size = 4,
        axis.label.size = 3,
        axis.labels = dlabels,
        legend.text.size = 9, 
        group.colours = radar_colour[6])+
  ggtitle("point6")+
  theme(legend.position="bottom") + 
  theme(text=element_text(family='Lato')) 


ggradar(clusters[7,], grid.label.size = 5,
        group.point.size = 4,
        axis.label.size = 3,
        axis.labels = dlabels,
        legend.text.size = 9,
        group.colours = radar_colour[7])+
  ggtitle("point7")+
  theme(legend.position="bottom") + 
  theme(text=element_text(family='Lato')) 


radar <- ggradar(clusters, 
                 font.radar = 'Lato', 
                 grid.label.size = 0,
                 group.point.size = 3,
                 axis.label.size = 3,
                 axis.labels = dlabels,
                 legend.text.size = 7)+
  ggtitle("7 cluster centers in 11 dimensions")+
  theme(legend.position="bottom") + 
  theme(text=element_text(family='Lato')) 

radar
#ggsave("clusterRadar.pdf",plot = radar)

```
